### ISSUE TITLE
in branch `ali` when create a new unit test the render(<App/>) returns and dome related error

### ISSUE THREAD

**Issue by aliscie** [aliscie/odoc#10]
when I rrun 
```tsx
import * as React from "react";
import App from "../../App";
import {render} from "@testing-library/react";
import configureStore from 'redux-mock-store';

import {initialState} from "../../redux/files";
import TestRapper from "../utls/tests_wrapper";

const mockStore = configureStore([]);


test("Test render app", async () => {
    let input: RegisterUser = {
        'name': ["string"],
        'description': ["Somthing"],
        'photo': [[]],
    };
    let res = await global.actor.register(input);
    let store = mockStore(initialState);
    render(<TestRapper>
        <App/>
    </TestRapper>);
});
```
I got ``` src/frontend/tests/React/App.test.tsx [ src/frontend/tests/React/App.test.tsx ]
Error: createRoot(...): Target container is not a DOM element.
 ❯ createRoot node_modules/react-dom/cjs/react-dom.development.js:29345:11
```

**Comment by ShivamAgarwal-code** [comment]
Hi, assign me this issue, will resolve this.
Thanks

**Comment by aliscie** [comment]
Ok you can go aheadSent from my iPhoneOn 9 Jul 2024, at 6:24 PM, Shivam Agarwal ***@***.***> wrote:﻿
Hi, assign me this issue, will resolve this.
Thanks

**Comment by ShivamAgarwal-code** [comment]
Hi @aliscie actually the error occurs when the createRoot function from react-dom cannot find the container element to render the React application into. This often happens if the element ID used in index.js does not match any element in the HTML file or if the tests are not setting up the DOM properly.
